### ISSUE TITLE
why do the spec.paths[myPath].responses={} object reset on server restart?

### ISSUE THREAD

**Issue by akhoury** [mpashkovskiy/express-oas-generator#40] opened 2019-11-04 17:11 UTC
I feel like it should just read the existing spec.json on file and "merge" it, I am using [`server.js`](https://github.com/mpashkovskiy/express-oas-generator/blob/master/server.js) as an example.

**Comment by sarpik** [comment] 2019-11-05 14:27
This happens [inside the `module.exports.init` method](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L147) - the parameter `aPredefinedSpec` is `undefined` by default, and if you don't pass anything in, the [`spec` variable will be set to `{}`](https://github.com/mpashkovskiy/express-oas-generator/blob/master/index.js#L13), which is what gets written to the file.

If you want to persist the old `json` file - you could read from it before using `expressOasGenerator.init()` and pass it in, like this:

```js
const fs = require("fs");
const express = require("express");
const expressOasGenerator = require("express-oas-generator");

/** you could create a simple utility function from this to keep things clean */
let oldSpecContent = {};

try {
  oldSpecContent = fs.readFileSync("path/to/spec.json", { encoding: "utf-8" });
} catch (err) {
  console.warn("Failed reading old spec", err);
  /** optionally throw the error here if you want to stop the server */
}

const app = express();
expressOasGenerator.init(app, oldSpecContent);
```

---

I (or maybe you?:) or someone else) can later create a PR to allow the package consumer (you, in this case) to provide a boolean if you'd like the spec to persist.
We'd like to finish https://github.com/mpashkovskiy/express-oas-generator/issues/35 before this thought to allow the parameters to be passed in as an object.

Hope this helps!

**Comment by mpashkovskiy** [comment] 2020-05-20 06:49
most likely we will add this functionality soon, but as for now @akhoury are you good with suggested by @sarpik workaround?

**Comment by maxiejbe** [comment] 2020-08-15 14:30
This is a dupe of #52, created by @kiprasmel.
Would you close it @mpashkovskiy ?

**Comment by mpashkovskiy** [comment] 2020-08-17 06:32
yes, let's move conversation to #52

**Closed by mpashkovskiy** 2020-08-17 06:32 UTC
